Fixes for renaming package

diff --git a/contrib/make_tgz b/contrib/make_tgz
--- a/contrib/make_tgz
+++ b/contrib/make_tgz
@@ -5,7 +5,7 @@ set -e
 CONTRIB="$(dirname "$(readlink -e "$0")")"
 ROOT_FOLDER="$CONTRIB"/..
 PACKAGES="$ROOT_FOLDER"/packages/
-LOCALE="$ROOT_FOLDER"/electrum/locale/
+LOCALE="$ROOT_FOLDER"/electrum_bsty/locale/
 
 if [ ! -d "$PACKAGES" ]; then
   echo "Run make_packages first!"
@@ -22,10 +22,10 @@ git submodule update --init
         exit 1
     fi
     for i in ./locale/*; do
-        dir="$ROOT_FOLDER"/electrum/$i/LC_MESSAGES
+        dir="$ROOT_FOLDER"/electrum_bsty/$i/LC_MESSAGES
         mkdir -p $dir
         msgfmt --output-file=$dir/electrum.mo $i/electrum.po || true
-        cp $i/electrum.po "$ROOT_FOLDER"/electrum/$i/electrum.po
+        cp $i/electrum.po "$ROOT_FOLDER"/electrum_bsty/$i/electrum.po
     done
 )
 
@@ -37,7 +37,7 @@ git submodule update --init
     echo "<<<"
 
     # we could build the kivy atlas potentially?
-    #(cd electrum/gui/kivy/; make theming) || echo "building kivy atlas failed! skipping."
+    #(cd electrum_bsty/gui/kivy/; make theming) || echo "building kivy atlas failed! skipping."
 
     python3 setup.py --quiet sdist --format=zip,gztar
 )
